heat_template_version: 2015-10-15

description: |
  #### Production

  Parse Server is an open-source version of the Parse backend that can be
  deployed to any infrastructure that can run Node.js.  This stack requires an
  existing MongoDB instance.

parameter_groups:
- label: Parse Settings
  parameters:
  - parse_url
  - parse_email
- label: Git Settings
  parameters:
  - git_repo_url
  - git_deploy_key
  - git_commit_sha
- label: rax-dev-params
  parameters:
  - server_image
  - secondary_template
  - ansible_branch
  - ansible_repo
parameters:
  #parse Customization
  parse_url:
    type: string
    default: example.com
    label: Site Domain
    description: Domain to use with Parse Server
    constraints:
    - allowed_pattern: "^[a-zA-Z0-9.-]{1,255}.[a-zA-Z]{2,15}$"
      description: Must be a valid domain name
      description: Only can contain A-Z and 0-9
  parse_email:
    type: string
    default: admin@example.com
    label: Parse Admin E-mail
    description: E-mail Address for Parse Admin User
  #Git Settings
  git_repo_url:
    type: string
    default: ""
    label: Git Repository URL
    description: |
      URL to Git repository, using either SSH or HTTPS to connect.  If you use
      SSH, you will need to specify the Git Deploy Key in order to connect.
  git_deploy_key:
    type: string
    default: ""
    label: Git Deploy Key
    description: |
      Deploy key to be used when connecting to the specified Git repository via
      SSH.  Not used when the Git URL is not specified or uses HTTPS
  git_commit_sha:
    type: string
    default: "HEAD"
    label: Git Commit
    description: |
      The SHA of the Git commit to pull and deploy.
  #Advanced Options
  server_flavor:
    type: string
    default: 4 GB General Purpose v1
    label: Server Flavor
    description: Flavor of Cloud Server to use
    constraints:
    - allowed_values:
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
  server_image:
    type: string
    default: f4bbbce2-50b0-4b07-bf09-96c175a45f4b
    constraints:
    - allowed_values:
      - f4bbbce2-50b0-4b07-bf09-96c175a45f4b
  server_count:
    type: number
    default: 0
    label: Number of Secondary Servers
    description: Number of secondary web nodes
    constraints:
      - range: { min: 0, max: 10 }
  secondary_template:
    type: string
    default: https://raw.githubusercontent.com/rackspace-orchestration-templates/parse-small/master/parse-small-secondary.yaml
    #default: https://raw.githubusercontent.com/rackspace-orchestration-templates/parse-small/stable/parse-small-secondary.yaml
    label: Secondary Template
    description: Template to use for secondary servers
  ansible_branch:
    type: string
    default: stable
    label: Git Branch or Tag for Ansible Roles
    description: The Ansible Roles will be pulled from Git, using the tag or branch provided
  ansible_repo:
    type: string
    default: https://github.com/rackspace-orchestration-templates/ansible-roles.git
    label: Git Repo for Ansible Roles
    description: The Ansible Roles will be pulled from Git, using the repo provided

resources:
  #Passwords
  parse_pass:
    type: OS::Heat::RandomString
  #SSH Key
  ssh_key:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true
  #Software Configurations
  upload_role_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      outputs:
      - name: results
      config:
        str_replace:
          template: |
            #!/bin/bash
            set -e
            git clone -b 'tag' --single-branch --progress repository /etc/ansible/roles > $heat_outputs_path.results 2>&1
          params:
            tag: { get_param: ansible_branch}
            repository: { get_param: ansible_repo }
  parse_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config: |
        ---
        - name: Install and configure parse
          hosts: localhost
          connection: local
          roles:
          - common
          - nginx
          - parse
  other_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      inputs:
      - default: "[]"
        name: lsync_servers
        type: CommaDelimitedList
      - default: "[]"
        name: lsync_dirs
        type: CommaDelimitedList
      - default: "[]"
        name: firewall_nodes
        type: CommaDelimitedList
      - default: "[]"
        name: firewall_node_rules
        type: CommaDelimitedList
      config: |
        ---
        - name: Install and configure other things
          hosts: localhost
          connection: local
          roles:
          - firewall
          - lsync
  deploy_roles:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: upload_role_config
      server:
        get_resource: parse_server
  deploy_parse:
    type: OS::Heat::SoftwareDeployment
    depends_on: deploy_roles
    properties:
      signal_transport: TEMP_URL_SIGNAL
      input_values:
        nginx_vhost_str: { get_param: parse_url }
        nginx_vhost_template: "parse"
        parse_cloud_code_main: "/home/parse/cloud/main.js"
        parse_database_uri: "mongodb://parse:password@localhost:27017/parseDb"
        parse_application_id: "your_application_id"
        parse_master_key: "your_master_key"
        parse_collection_prefix: ""
        parse_client_key: ""
        parse_rest_api_key: ""
        parse_dotnet_key: ""
        parse_javascript_key: ""
        parse_file_key: ""
        parse_facebook_app_ids: ""
        parse_git_key: { get_param: git_deploy_key }
        parse_git_repo: { get_param: git_repo_url }
        parse_git_version: { get_param: git_commit_sha }
        tz: "America/Chicago"
      config:
        get_resource: parse_config
      server:
        get_resource: parse_server
  deploy_other:
    type: OS::Heat::SoftwareDeployment
    depends_on: deploy_parse
    properties:
      signal_transport: TEMP_URL_SIGNAL
      input_values:
        lsync_private_key: { get_attr: [ssh_key, private_key] }
        lsync_dirs: ['/home/parse']
        lsync_servers: { get_attr: [parse_secondary, private_ip] }
        firewall_global_rules: [ "0.0.0.0,0,22,tcp", "0.0.0.0,0,80,tcp", "0.0.0.0,0,443,tcp"]
        #firewall_nodes: { get_attr: [parse_secondary, private_ip] }
        firewall_node_rules: []
      config:
        get_resource: other_config
      server:
        get_resource: parse_server
  #Master Server
  parse_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: "OS::stack_name" }
      image: { get_param: server_image }
      flavor: { get_param: server_flavor }
      key_name: { get_resource: ssh_key }
      software_config_transport: POLL_TEMP_URL
      config_drive: true
      user_data_format: SOFTWARE_CONFIG
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        build_config: "backup_agent_only,monitoring_defaults"
  #Monitoring Checks
  parse_server_http_check:
    type: Rackspace::CloudMonitoring::Check
    depends_on: deploy_parse
    properties:
      entity: { get_resource: parse_server }
      type: remote.http
      label:
        str_replace:
          template: stack Master HTTP Check
          params:
            stack: { get_param: "OS::stack_name" }
      details:
        url:
          str_replace:
            template: "http://ipaddr"
            params:
              ipaddr: { get_attr: [parse_server, accessIPv4] }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }
      period: 120
      timeout: 10
      monitoring_zones_poll:
      - Northern Virginia (IAD)
      - Chicago (ORD)
      - Dallas Fort Worth (DFW)
      - London (LON)
      target_hostname: { get_attr: [parse_server, accessIPv4] }
      target_receiver: IPv4
  load_balancer_http_check:
    type: Rackspace::CloudMonitoring::Check
    depends_on: load_balancer
    properties:
      entity: { get_resource: parse_server }
      type: remote.http
      label:
        str_replace:
          template: stack Load Balancer HTTP Check
          params:
            stack: { get_param: "OS::stack_name" }
      details:
        url:
          str_replace:
            template: "http://ipaddr"
            params:
              ipaddr: { get_attr: [parse_server, accessIPv4] }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }
      period: 120
      timeout: 10
      monitoring_zones_poll:
      - Northern Virginia (IAD)
      - Chicago (ORD)
      - Dallas Fort Worth (DFW)
      - London (LON)
      target_hostname: { get_attr: [load_balancer, PublicIp] }
      target_receiver: IPv4
  #Cloud Backup
  parse_backup:
    type: Rackspace::Cloud::BackupConfig
    depends_on: parse_server
    properties:
      server: { get_resource: parse_server }
      BackupConfigurationName:
        str_replace:
          template: stack Weekly Backup
          params:
            stack: { get_param: "OS::stack_name" }
      Inclusions:
      - FilePath: "/home/parse"
        FileItemType: "Folder"
      NotifyFailure: true
      NotifyRecipients: { get_param: parse_email }
      TimeZoneId: Central Standard Time
      StartTimeAmPm: AM
      StartTimeHour: 1
      StartTimeMinute: 0
      HourInterval: null
      DayOfWeekId: 0
      Frequency: "Weekly"
      VersionRetention: 30
  #Secondary Server
  parse_secondary:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: server_count }
      resource_def:
        type: { get_param: secondary_template }
        properties:
          ssh_key: { get_resource: ssh_key }
          parent_stack_id: { get_param: "OS::stack_id" }
          server_image: { get_param: server_image }
          server_flavor: { get_param: server_flavor }
          apache_default_domain: { get_param: parse_url }
          master_server: { get_attr: [ parse_server, networks, private, 0] }
          server_name:
            str_replace:
              template: stack-secondary-%index%
              params:
                stack: { get_param: "OS::stack_name" }
          ansible_branch: { get_param: ansible_branch}
          ansible_repo: { get_param: ansible_repo }
  #Cloud Load Balancer
  load_balancer:
    type: Rackspace::Cloud::LoadBalancer
    depends_on:
    - deploy_parse
    - parse_secondary
    properties:
      name:
        str_replace:
          template: stack_Load_Balancer
          params:
            stack: { get_param: "OS::stack_name" }
      nodes:
      - addresses: [ { get_attr: [parse_server, networks, private, 0] } ]
        port: 443
        condition: ENABLED
      - addresses: { get_attr: [parse_secondary, private_ip] }
        port: 443
        condition: ENABLED
      port: 443
      protocol: HTTPS
      httpsRedirect: true
      algorithm: ROUND_ROBIN
      contentCaching: ENABLED
      virtualIps:
      - type: PUBLIC
        ipVersion: IPV4
      metadata:
        rax-heat: { get_param: "OS::stack_id" }

outputs:
  ssh_private_key:
    description: SSH Private Key
    value:
      get_attr: [ssh_key, private_key]
  server_ip:
    description: Server Public IP
    value:
      get_attr: [parse_server, accessIPv4]
  parse_api_url:
    description: Parse API URL
    value:
      str_replace:
        template: https://url/parse
        params:
          url: { get_param: parse_url }
